import Link from "next/link";
import { BarChart3, ClipboardList, FileText, Megaphone, Plus, ShieldAlert } from "lucide-react";
import { getCurrentUser } from "@/lib/auth";
import { listConcerns, store } from "@/lib/demo-store";
import { ActionCard, ActivityRow, AnnouncementRow, MetricCard } from "@/components/ui";
import { PageReveal } from "@/components/page-reveal";

export default async function ResidentHome() {
  const user = await getCurrentUser();
  // The protected layout owns redirects. Avoid throwing while Next renders this page in parallel.
  if (!user || user.role !== "resident") return null;
  const concerns = listConcerns(user.id);
  const resolved = concerns.filter((concern) => concern.status === "resolved").length;
  const active = concerns.filter((concern) => !["resolved", "rejected"].includes(concern.status)).length;
  return <main className="page-main"><PageReveal><div className="page-header"><div><p className="eyebrow">Resident workspace</p><h1>Good to see you, {user.fullName.split(" ")[0]}.</h1><p>Keep a record of what needs attention, what is underway, and what changed.</p></div><div className="page-header-actions"><Link className="button primary" href="/app/report"><Plus size={16} /> Report a concern</Link></div></div><div className="metrics"><MetricCard icon={ClipboardList} label="My concerns" value={concerns.length} detail="All submitted reports" /><MetricCard icon={BarChart3} label="Active" value={active} detail="Needs follow-up" /><MetricCard icon={FileText} label="Documents" value={store.documentRequests.filter((request) => request.residentId === user.id).length} detail="Requests submitted" /><MetricCard icon={ShieldAlert} label="Resolved" value={resolved} detail="Documented outcomes" /></div><div className="grid-2"><section className="card card-pad"><div className="card-head"><div><h2>My recent activity</h2><p>Follow the latest updates in your workspace.</p></div><Link className="text-link small" href="/app/activity">View all</Link></div>{concerns.length ? <div className="activity-list">{concerns.slice(0, 4).map((concern) => <ActivityRow key={concern.id} concern={concern} />)}</div> : <div className="empty-state"><h3>Start a clear record</h3><p>Report a concern so you can follow its progress from submission to resolution.</p><Link className="button secondary" href="/app/report">Report a concern</Link></div>}</section><section className="card card-pad"><div className="card-head"><div><h2>Community notices</h2><p>Useful guidance from your service desk.</p></div><Megaphone size={18} color="var(--teal)" /></div><div className="announcement-list">{store.announcements.slice(0, 3).map((item) => <AnnouncementRow key={item.id} {...item} />)}</div></section></div><section style={{ marginTop: 20 }}><div className="card card-pad"><div className="card-head"><div><h2>What do you need today?</h2><p>Choose a direct path into the service desk.</p></div></div><div className="action-grid"><ActionCard href="/app/report" icon={ClipboardList} title="Report a concern" description="Describe a community issue with location and evidence." label="Start report" /><ActionCard href="/app/documents" icon={FileText} title="Request a document" description="Submit a public-service document request and track it." label="Open requests" /><ActionCard href="/app/emergency" icon={ShieldAlert} title="Emergency resources" description="Find quick access to emergency and support contacts." label="View resources" /></div></div></section></PageReveal></main>;
}
