"use client";

import { FormEvent, useEffect, useState } from "react";
import type { Announcement, EmergencyContact } from "@/lib/types";

export function ContentManager() {
  const [announcements, setAnnouncements] = useState<Announcement[]>([]); const [contacts, setContacts] = useState<EmergencyContact[]>([]); const [title, setTitle] = useState(""); const [excerpt, setExcerpt] = useState(""); const [label, setLabel] = useState(""); const [number, setNumber] = useState(""); const [description, setDescription] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { Promise.all([fetch("/api/announcements").then((response) => response.json()), fetch("/api/emergency").then((response) => response.json())]).then(([a, e]) => { setAnnouncements(a.announcements); setContacts(e.contacts); }); }, []);
  async function addAnnouncement(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/announcements", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, excerpt }) }); const result = await response.json(); if (response.ok) { setAnnouncements((current) => [result.announcement, ...current]); setTitle(""); setExcerpt(""); setMessage("Announcement published."); } }
  async function addContact(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/emergency", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label, number, description }) }); const result = await response.json(); if (response.ok) { setContacts((current) => [...current, result.contact]); setLabel(""); setNumber(""); setDescription(""); setMessage("Emergency contact added."); } }
  return <div className="grid-2"><section className="card card-pad"><div className="card-head"><div><h2>Announcements</h2><p>Create a short, resident-facing service notice.</p></div></div>{message && <div className="notice success">{message}</div>}<form className="form-stack" onSubmit={addAnnouncement}><div className="field"><label htmlFor="title">Title</label><input id="title" value={title} onChange={(event) => setTitle(event.target.value)} required /></div><div className="field"><label htmlFor="excerpt">Excerpt</label><textarea id="excerpt" value={excerpt} onChange={(event) => setExcerpt(event.target.value)} required /></div><button className="button primary">Publish announcement</button></form><div className="announcement-list" style={{ marginTop: 22 }}>{announcements.slice(0, 5).map((item) => <div key={item.id} className="announcement-row"><span className={`priority-dot ${item.priority === "high" ? "high" : ""}`} /><div><h3>{item.title}</h3><p>{item.excerpt}</p></div></div>)}</div></section><section className="card card-pad"><div className="card-head"><div><h2>Emergency resources</h2><p>Keep public support contacts clear and current.</p></div></div><form className="form-stack" onSubmit={addContact}><div className="field"><label htmlFor="label">Label</label><input id="label" value={label} onChange={(event) => setLabel(event.target.value)} required /></div><div className="field"><label htmlFor="number">Number</label><input id="number" value={number} onChange={(event) => setNumber(event.target.value)} required /></div><div className="field"><label htmlFor="description">Description</label><textarea id="description" value={description} onChange={(event) => setDescription(event.target.value)} required /></div><button className="button primary">Add contact</button></form><div className="contact-list" style={{ marginTop: 22 }}>{contacts.map((contact) => <div className="contact-row" key={contact.id}><div><h3>{contact.label}</h3><p>{contact.description}</p></div><span className="contact-number">{contact.number}</span></div>)}</div></section></div>;
}
