"use client";

import { FormEvent, useEffect, useState } from "react";
import { ArrowUpRight, FileText } from "lucide-react";
import type { DocumentRequest } from "@/lib/types";
import { documentStatusLabels } from "@/lib/types";

export function DocumentCenter() {
  const [requests, setRequests] = useState<DocumentRequest[]>([]); const [types, setTypes] = useState<string[]>([]); const [documentType, setDocumentType] = useState(""); const [purpose, setPurpose] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function load() { const response = await fetch("/api/documents", { cache: "no-store" }); const result = await response.json(); if (response.ok) { setRequests(result.requests); setTypes(result.documentTypes); setDocumentType(result.documentTypes[0] ?? ""); } }
  // Data loading is an external synchronization; the state update is intentionally async.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, []);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); setMessage(""); const response = await fetch("/api/documents", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ documentType, purpose }) }); const result = await response.json(); setLoading(false); if (!response.ok) { setError(result.error); return; } setRequests((current) => [result.request, ...current]); setPurpose(""); setMessage(`Request ${result.request.reference} submitted.`); }
  return <div className="grid-2"><section className="card card-pad"><div className="card-head"><div><h2>New document request</h2><p>Choose the document and tell the service desk what it is for.</p></div><FileText size={18} color="var(--teal)" /></div>{error && <div className="notice error">{error}</div>}{message && <div className="notice success">{message}</div>}<form className="form-stack" onSubmit={submit}><div className="field"><label htmlFor="documentType">Document type</label><select id="documentType" value={documentType} onChange={(event) => setDocumentType(event.target.value)}>{types.map((type) => <option key={type}>{type}</option>)}</select></div><div className="field"><label htmlFor="purpose">Purpose</label><textarea id="purpose" value={purpose} onChange={(event) => setPurpose(event.target.value)} placeholder="Tell us what you need this for." /></div><button className="button primary" disabled={loading}>{loading ? "Submitting…" : "Submit request"}</button></form></section><section className="card card-pad"><div className="card-head"><div><h2>My requests</h2><p>Use the reference if you need to follow up.</p></div></div>{requests.length ? <div className="activity-list">{requests.map((request) => <div className="activity-row" key={request.id}><div className="activity-row-main"><strong>{request.documentType}</strong><small>{request.reference} · {new Date(request.submittedAt).toLocaleDateString()}</small></div><div className="activity-row-end"><span className={`status-badge ${request.status === "released" ? "resolved" : request.status === "rejected" ? "rejected" : "received"}`}>{documentStatusLabels[request.status]}</span>{request.status === "released" && <a className="text-link small" href={`/verify/${request.reference}`} target="_blank" rel="noreferrer">Verify <ArrowUpRight size={13} /></a>}</div></div>)}</div> : <div className="empty-state"><h3>No requests yet</h3><p>Your document requests and status changes will appear here.</p></div>}</section></div>;
}
